config_subvol.toml

Noticed a couple typos while looking at this config

Fix typos in config_subvol.toml

---

src/ugrd/kmod/kmod.py
src/ugrd/kmod/kmod.toml

Add a no_kmod option that enables using ugrd with kernels built without kernel module support entirely.

feat(kmod): add no_kmod option

---

examples/example.toml
readme.md
src/ugrd/fs/btrfs.toml
src/ugrd/fs/mounts.toml

Make most mounts mount under dirs under the root mountpoint, helps keep things simpler, and makes it less likely that a user can do something like define a mount at /mnt and mess things up at runtime.
Moved the btrfs subvol selector mountpoint to the root as well.

simplify default mounts/mountpoints

---

hooks/kernel-install/52-ugrd.install

- Port script to POSIX sh
- Fix logic in non-add command handling (|| -> &&)
- Consistently use quoting and braces for variables

feat(kernel-install): port to POSIX sh, fixups

---

docs/configuration.md
examples/livegui.toml
src/ugrd/base/base.py
src/ugrd/base/base.toml
src/ugrd/fs/livecd.py
src/ugrd/fs/livecd.toml
src/ugrd/fs/mounts.py
src/ugrd/fs/mounts.toml
src/ugrd/fs/overlayfs.py
src/ugrd/fs/overlayfs.toml
src/ugrd/kmod/kmod.py

Also improve log/error message consistency, simplify mounts module.

Separate overlayfs functionality from the livecd module

---

src/ugrd/base/keymap.py

The keymap module scans keymap files for include directives to identify further keymap files to be included. Keymap files, however, have different encodings. The default "utf-8" of decode() produces errors when an invalid character is found, say, when a ISO-8859 character is found.
This is, for instance, the case for keymaps/i386/include/compose.inc in the upstream repository, causing ugrd to fail. Greetings to Bernhard Rosenkränzer.
Add an option to decode() to ignore errors, which should be safe assuming that the include directives are not affected. A more involved solution would be to use the 'magic' package for the 'file' utility.

keymap: Ignore utf-8 decoding errors

---

src/ugrd/base/test.py
tests/test_output_paths.py

add tests for TMPDIR usage at build time
improve relative out file test to not leave test files in the dir where it is run

Improve testing

---

src/ugrd/fs/mounts.py

but when type cannot be determined, such as when LUKS headers are detached

improve error message for when the root is on a device mapper deivce

---

docs/configuration.md
src/ugrd/base/debug.py
src/ugrd/base/debug.toml
src/ugrd/initramfs_dict.py

At the moment the debug module has a hard-coded dependency on `nano` as the editor.
This adds code to detect the system/preferred editor based on the `EDITOR` environment variable, and provides the `editor` parameter in config to override it.
In case the user is running from a terminal that (for whatever reason) has set the `EDITOR` variable to something unusual, it will also throw a warning when they're not in a predefined list of regular values.
(also found a missing bracket in a join function in `initramfs_dict.py` that caused  a runtime error when testing, so I just added that in too)

Debug select editor

---

src/ugrd/base/debug.py
src/ugrd/base/debug.toml

Fixed up that issue with the validation by getting it to check the basename using pathlib, in case the user specifies the full path to the editor.
I also used ALEFix to clean up the formatting, so all the indentation stuff should be alright now (hopefully lol)
Did more testing with debug mode, I found that without include `/usr/share/terminfo/l/linux` as a dependency `nano` will refuse to start. `vim`/`vi` will still open, but will complain about it. I added it as a dependency for the module, since it's needed for pretty much any editor and having it available makes shells happier too.
Had to remove `emacs` from the EXPECTED_EDITORS list, I wanted to include it because it's a common editor, however once all the libraries are pulled in it adds quite a bit to the image size. In addition …

Fixes to the validation bug and formatting with the editor select code

---

src/ugrd/crypto/cryptsetup.py
src/ugrd/crypto/cryptsetup.toml

this should be better flow control, and includes the header file info in the initramfs for usage.
Counts key unlock commands as a failure to not attempt an empty key file.
If multiple luks devices are used, checks them individually for better failure recovery.
The open_crypt_dev function should be easier to use in recovery cases.

refactor cryptsetup unlocks

---

hooks/installkernel/52-ugrd.install

This changes the installkernel hook to use the staging area that will be introduced in the next version.

52-ugrd.install: install to staging area

---

src/ugrd/fs/mounts.py

since config changes should not be made in the init runlevel, and even if additional mounts were added, they would not affect the existing fstab file, since it was already generated by generate_fstab

don't run mount_fstab if a fstab is not in the initramfs

---

docs/configuration.md
src/ugrd/base/test.py
src/ugrd/base/test.toml
src/ugrd/fs/resume.py
src/ugrd/fs/resume.toml
src/ugrd/fs/test_image.py
src/ugrd/fs/test_image.toml

Adds a new late_resume parameter, which moves the trigger point from init_early to init_premount.
This allows cryptsetup and LVM to initialize before the system attempts to resume, making encrypted or otherwise non-trival-to-access swap partitions accessible.
In addition it will use allow using resume=UUID=* to specify the resume device, as any partitions that aren't directly on disk don't have a PARTUUID.
This is a continuation of [this pull request](https://github.com/desultory/ugrd/pull/139), and will add runtime checks and build-time tests to try to determine whether resume is safe before going ahead.
It's hard to make it foolproof as resume after allowing access to file systems, while generally safe as long as they're mounted RO is modified, is prone to lots of edge cases. The kernel …

Support for resume from encrypted swap

---

src/ugrd/net/net.py

net_device_mac must be set for device resolution at runtime. Warn if this is set but the net_device is not. This important when building for another system.

warn when net_device_mac is set but net_device isn't

---

docs/runtime_usage.md
src/ugrd/base/base.py
src/ugrd/base/bell.py
src/ugrd/base/bell.toml
src/ugrd/base/cmdline.py
src/ugrd/base/cmdline.toml
src/ugrd/base/debug.py
src/ugrd/fs/ext4.py
src/ugrd/fs/f2fs.py
src/ugrd/fs/livecd.py
src/ugrd/fs/livecd.toml
src/ugrd/fs/mounts.toml

certain cmdline args such as "debug" should never be handled by userspace systems. Others, such as "resume" "root", or "init" related ones must be handled by the initramfs, unless they are ignored entirely.
Checks that vars defined in the build process have namespaces unless specific exclusions are defined.

namespace cmdline args when necessary

---

src/ugrd/base/test.toml
src/ugrd/initramfs_dict.py

This prevents errors when modules have this defined, but the test module is not loaded.

move test_copy_config into the base config dict

---

src/ugrd/fs/mounts.py

this helps if there is ": " in a label or similar

only split the first ": "

---

src/ugrd/fs/cpio.py

kmod_init may be populated by builtin modules.

check that the kernel version is defined before adding it to the archive name

---

src/ugrd/main.py

red is used for import levels which were not used
yellow is used for hooks which were not used

colorize print-init

---

src/ugrd/kmod/kmod.py

set the out_file to be next to the detected kernel image for arch systems

---

src/ugrd/base/core.py
src/ugrd/base/core.toml

Maybe this should be parsed, it may add search paths which are not relevant.
Possibly the detected library paths could be used to build this file manually near the end of the build process

add detection for the musl search path file

---

docs/configuration.md
src/ugrd/fs/mounts.py
src/ugrd/fs/mounts.toml

don't misuse this kernel arg, add a namespaced arg that corresponds to internal config

don't use rootdelay for mount timeout, add ugrd_mount_timeout

---

src/ugrd/kmod/input.py
src/ugrd/kmod/input.toml

set a threshold at 25 keys as certain devices may have key event capabilities but are not a proper keyboard.

upgrade the input detection module to look for keyboard like devices

---

src/ugrd/crypto/cryptsetup.py

As discussed on discord.
get_crypt_device started a subshell and ran a new init, swallowing logs and input and causing other spookiness.
Just edited on github for the moment as it is so simple, but I will do due diligence and clone the repo properly asap.

BUGFIX: Fix odd subshell behaviour if device is not first detected

---

src/ugrd/base/cmdline.py

only include args with a newline/whitespce before them, exclude _, ., etc.

improve deprecated cmdline arg check

---

src/ugrd/fs/fakeudev.py

My image throws a kernel panic:
```
* Running fsck on: /dev/mapper/luksvg-gentoo
/dev/mapper/luksvg-gentoo: clean, 635733/20721152 files, 6987471/114859008 blocks
/etc/profile: line 420: /sys/block/dm-0/uevent: Success
[   10.201899] Kernel panic - not syncing: Attempted to kill init! exitcode=0x00000100
[   10.203771] CPU: 0 PID: 1 Comm: init Not tainted 6.12.34-gentoo-dist #1
```
The problem is sourcing the `uevent` file. I'm not exactly sure how it crashed the init but it doesn't seem we have to read from there.
Also, I could disable `fake_dm_udev`, by commenting the line in `init` file, and my systemd system booted just fine. Not sure if #181 was necessary.
My setup:
> Ext4 rootfs partition on LVM and LVM on LUKS.
> Systemd 257.7
I haven't changed default config and ugrd was able to …

fix fs.fakeudev, do not source uevent file

---

src/ugrd/fs/mounts.py
src/ugrd/kmod/kmod.toml
src/ugrd/kmod/platform.py
src/ugrd/kmod/platform.toml
src/ugrd/kmod/vm.toml

ensures necessary drivers are added depending on the vm platform
add a `virtual_machine` var so modules can act accordingly. Make the mounts scsi driver detection consider this and add virtio_scsi

add basic vm platform detection

---

src/ugrd/base/banner.py

printing "kernel version" for the kver used at build time is confusing

make the banner print "built for kernel version"
