desultory/ugrd

readme.md, src/ugrd/crypto/cryptsetup.py, src/ugrd/crypto/cryptsetup.toml
Add a toggle for validation of cryptsetup keyfiles.
=> Key validation toggle

pyproject.toml, src/ugrd/base/base.py, src/ugrd/base/base.toml, src/ugrd/base/core.py, src/ugrd/base/debug.py, src/ugrd/base/keymap.py, src/ugrd/crypto/cryptsetup.py, src/ugrd/crypto/smartcard.py, src/ugrd/fs/btrfs.py, src/ugrd/fs/lvm.py, src/ugrd/fs/mounts.py, src/ugrd/fs/mounts.toml, src/ugrd/generator_helpers.py, src/ugrd/initramfs_dict.py, src/ugrd/initramfs_generator.py, src/ugrd/kmod/kmod.py
Replace confusing check_dict usage with simpler contains and unset decorators.
=> Clean dict checks

src/ugrd/base/core.py, src/ugrd/base/core.toml, src/ugrd/kmod/kmod.py, src/ugrd/kmod/kmod.toml
Add xz deps dependency type.
Decompress compress kmod firmware.
=> Module firmware decompression/xz deps

docs/configuration.md, pyproject.toml, src/ugrd/base/plymouth.toml, src/ugrd/fs/mounts.py, src/ugrd/fs/mounts.toml
=> remove remake-mountpoints as it was never really used

src/ugrd/kmod/nosound.toml
=> Added two kmods to exlude

src/ugrd/base/base.py, src/ugrd/base/base.toml, src/ugrd/fs/mounts.py, src/ugrd/fs/mounts.toml, src/ugrd/generator_helpers.py
add retries helper function for bash scripts.
Make mounts automatically retry 5 times by default.
=> add retries function

examples/example.toml, pyproject.toml, src/ugrd/crypto/cryptsetup.toml, src/ugrd/fs/mounts.py, src/ugrd/kmod/kmod.py, src/ugrd/kmod/kmod.toml
hopegully now lsmod won't be required by default for most setups.
=> Autodetect root block device drivers

src/ugrd/kmod/kmod.py
also fix it not actually running
=> add validate toggle for arch kernel version check

docs/configuration.md, src/ugrd/crypto/cryptsetup.py, src/ugrd/crypto/cryptsetup.toml, src/ugrd/fs/cpio.py
also fix bug with file extensions when setting --compress via command line
=> Add toggle for cryptsetup header validation

src/ugrd/crypto/cryptsetup.py
don't pull incorrect aes module
=> interesting the 'aes' module is not what we want

src/ugrd/kmod/kmod.py
improve comments
fix softdep resolution
=> Improve comments, don't resolve dependencies of builtin kmods

src/ugrd/main.py
don't run if unrecognized args are passed, black format the main file
=> fix inconsistent use of sets and lists, enable strict argument parsing

src/ugrd/__init__.py, src/ugrd/base/base.py, src/ugrd/base/checks.py, src/ugrd/base/core.py, src/ugrd/crypto/cryptsetup.py, src/ugrd/fs/btrfs.py, src/ugrd/fs/mounts.py, src/ugrd/initramfs_generator.py, src/ugrd/main.py
=> improve exception handling for validation/autodetect errors

docs/configuration.md
https://github.com/desultory/ugrd/pull/164
=> fixed issue where validation incorectly fails & cleaned up formatting

src/ugrd/crypto/cryptsetup.py
this should probably be defined per-mount
=> handle cryptsetup_trim

src/ugrd/kmod/kmod.py
this fails in cases where lspci would detect multiple kmods per device, but that often results in extra kmods being pulled and pointless warnings.
=> don't actually use lspci

src/ugrd/fs/livecd.py, src/ugrd/fs/livecd.toml, src/ugrd/fs/overlayfs.toml, src/ugrd/main.py
also add a cmdline arg for setting the squashfs image name add improved checks for runtime usage
=> improve livecd module to take dynamic labels/squashfs targets

src/ugrd/kmod/kmod.py, src/ugrd/kmod/kmod.toml
should help prevent unused modules from being imported
=> only add kmod deps after all kmods have been resolved, don't add ignored modules if they are removed later

src/ugrd/fs/mdraid.py, src/ugrd/fs/mdraid.toml
https://github.com/desultory/ugrd/issues/225
=> improve mdadm init and resume support

src/ugrd/kmod/kmod.py
fix bug introduced in the last PR
=> fix broken/inverted logic

src/ugrd/kmod/kmod.py
=> improve exception handling for kernel image version detection

src/ugrd/initramfs_dict.py
Ensures values with processors in the same module are processed in the correct order.
=> improve arg processing order, queue values first and process later

src/ugrd/base/core.py
If pulled binaries have a shebang, pull the interpreter. This approach is very basic and doesn't truly consider all interpreter dependencies are pulled.
This is mostly useful for mulicall binaries.
=> check the shebang of imported binaries for an interpreter

readme.md, src/ugrd/fs/test_image.py, src/ugrd/kmod/__init__.py, src/ugrd/kmod/kmod.py, src/ugrd/main.py, tests/fs/f2fs.toml, tests/test_filesystems.py
Add _copy_fs_contents to mount and copy contents into test filesystems in a more generic manner.
=> Add f2fs tests, standardize test mounting/population, add MissingModuleError exception

src/ugrd/crypto/cryptsetup.py
LUKS1 is only supported as much as it needs to be, don't validate LUKS1 headers and provide info about configuring for detached headers or headers which should not be validated.
=> improve error message for failed header validation

src/ugrd/kmod/kmod.py
inform the user of requred modules, as no_kmod disables most checks. log kmod names on firmware check failure
=> improve log messages when no_kmod is enabled

src/ugrd/kmod/kmod.py
fix bug introduced in prior patch https://github.com/desultory/ugrd/pull/273
=> don't double join ignored kmod list string

src/ugrd/base/test.py, src/ugrd/fs/test_image.py, tests/fs/f2fs.toml
add extra padding for btrfs/f2fs filesystems in test_image itslf
=> improve test loop, stdout ANSI filtering

src/ugrd/fs/btrfs.py, src/ugrd/fs/mounts.py
do this instead of directly modifying the MOUNTS_ROOT_OPTIONS var
=> use "root_extra_options" when root mount options need dynamic changes

src/ugrd/base/debug.toml, src/ugrd/fs/mounts.toml
sleep has not been used here for a while
=> move sleep to the debug module, don't include in the mount module

src/ugrd/base/core.py, src/ugrd/kmod/kmod.py
=> handle both .zst and .zstd as known extensions for zstandard compression

src/ugrd/kmod/nonetwork.toml
include igc. Thanks for your help on irc
=> Include 'igc' in the nonetwork.toml list

src/ugrd/kmod/input.py, src/ugrd/kmod/input.toml, src/ugrd/kmod/kmod.toml
maybe there is a better way to enumerate this info, in the mean time this helps
=> add module to attempt to autodetect and add active input kmods

src/ugrd/fs/livecd.py, src/ugrd/fs/livecd.toml
fix broken update for namespaced cmdline args. Issue was hidden becaue of the recovery entry
=> use ugrd_squashfs_image instead of squashfs_image

src/ugrd/fs/ext4.toml, src/ugrd/fs/f2fs.toml
https://github.com/desultory/ugrd/issues/297
=> ensure fsck runs before mount_late

src/ugrd/crypto/cryptsetup.py
header file info would not be added to the image if a path was used for the device. This should fix that. also improves comments
Closes: https://github.com/desultory/ugrd/issues/302
=> add header file export before path check
